### ISSUE TITLE
null is not an object (evaluating '_ExpoRandom.default.getRandomBytesAsync')]

### ISSUE THREAD

**Issue by Dabisilva** [murilo-campaner/react-native-juno-rn-card-hash#1]
Quando tento pegar o Hash está retornando esse erro, mesmo antes de usar, no momento que inicio o app já mostra o erro, mas ele vem no console.log() também quando faço a requisição. 
Estou usando expo e só instalei a lib @expo/browser-polyfill que foi requisitada, queria uma resposta pra esse erro se possivel

**Comment by murilo-campaner** [comment]
Olá @Dabisilva 

Você está  usando qual versão do expo?
A biblioteca funciona a partir do Expo 39
